# frozen_string_literal: true

require 'digest'
require 'date'
require 'json'
require 'time'

module TravelRouting
  # Validates only the explicit route proposal generated by the personal AI UI.
  # The frozen Specialist scheduling contract remains a separate boundary.
  class RecommendationGuard
    LOCAL_PROVENANCE = Object.new.freeze
    LIFETIME_SECONDS = 15 * 60
    FAILURE_MESSAGE = '移動経路または予定の空きを再確認できませんでした。予定は保存せず、もう一度候補を作成してください。'
    EXPIRED_MESSAGE = '移動候補の有効期限が切れました。もう一度候補を作成してください。'

    class Rejected < StandardError; end

    def self.routing?(payload)
      payload.is_a?(Hash) && (payload.key?('routing') || payload.key?(:routing))
    end

    def self.public_payload(value)
      case value
      when Hash
        value.each_with_object({}) do |(key, child), result|
          result[key] = public_payload(child) unless key.to_s == 'routing'
        end
      when Array then value.map { |child| public_payload(child) }
      else value
      end
    end

    def self.prepare_response(response, user:, now: Time.current)
      new(user: user, now: now).prepare_response(response)
    end

    def initialize(user:, now: nil, provider: nil)
      @user = user
      @now = now || Time.current
      @use_current_clock = now.nil?
      @provider = provider
    end

    def prepare_response(response)
      candidates = Array(response[:recommendations])
      return response unless candidates.any? { |candidate| self.class.routing?(candidate['payload'] || candidate[:payload]) }
      reject! unless response[:routes_provenance].equal?(LOCAL_PROVENANCE)

      prepared = candidates.map do |candidate|
        copy = candidate.deep_stringify_keys.deep_dup
        next copy unless self.class.routing?(copy['payload'])

        validate_kind!(copy['kind'])
        payload = copy.fetch('payload')
        routing, events = validate_payload!(payload)
        routing['expires_at'] ||= (timestamp!(routing['checked_at']) + LIFETIME_SECONDS).iso8601
        validate_freshness!(routing)
        validate_places!(routing)
        validate_buffer!(routing)
        validate_calendar!(events)
        routing['approval_digest'] = approval_digest(payload)
        copy
      end
      response.merge(recommendations: prepared)
    rescue Rejected, KeyError, TypeError, ArgumentError
      response.merge(assistant_message: FAILURE_MESSAGE, recommendations: [],
        provider: 'rails-google-routes-guard-v1', tool_invocations: [])
    end

    def revalidate!(recommendation)
      return unless self.class.routing?(recommendation.payload)

      reject! unless recommendation.user_id == @user.id && recommendation.ai_conversation.scope_type == 'home'
      validate_kind!(recommendation.kind)
      lock_calendar!
      payload = recommendation.payload.deep_stringify_keys
      routing, events = validate_payload!(payload)
      reject! unless routing['approval_digest'].is_a?(String) &&
        ActiveSupport::SecurityUtils.secure_compare(routing['approval_digest'], approval_digest(payload))
      validate_freshness!(routing)
      validate_places!(routing)
      validate_buffer!(routing)
      validate_calendar!(events)

      result = provider.call(**routing.fetch('request').symbolize_keys)
      reject! unless result.respond_to?(:success?) && result.success?
      validate_result!(result.to_h.stringify_keys, events, routing)

      # The network request can take time. Recheck time and current canonical rows
      # again before the caller performs any Event/feedback write.
      @now = Time.current if @use_current_clock
      reject! if timestamp!(events.first['start_at']) < @now
      validate_freshness!(routing)
      validate_places!(routing)
      validate_buffer!(routing)
      validate_calendar!(events)
      true
    rescue Rejected
      raise
    rescue StandardError
      reject!
    end

    private

    def provider
      @provider ||= GoogleRoutesProvider.new
    end

    def validate_kind!(kind)
      reject! unless kind == 'draft_event'
    end

    def validate_payload!(payload)
      routing = payload['routing']
      reject! unless routing.is_a?(Hash) && routing['source'] == 'google_routes'
      request = routing['request']
      reject! unless request.is_a?(Hash) &&
        (request.except('transit_mode').keys.sort == %w[departure_time destination mode origin] ||
         request.except('transit_mode').keys.sort == %w[arrival_time destination mode origin])
      reject! unless %w[WALK DRIVE TRANSIT].include?(request['mode'])
      reject! if request.key?('transit_mode') &&
        (request['mode'] != 'TRANSIT' || !%w[RAIL BUS].include?(request['transit_mode']))
      reject! if request.key?('arrival_time') && request['mode'] != 'TRANSIT'
      timestamp!(request['departure_time'] || request['arrival_time'])
      %w[origin destination].each do |key|
        endpoint = request[key]
        reject! unless endpoint.is_a?(String) && endpoint.present? && endpoint.bytesize <= 1024 ||
          endpoint.is_a?(Hash) && endpoint.present?
      end
      events = payload['events']
      reject! unless events.is_a?(Array) && events.length.between?(1, 2)
      events.each do |event|
        reject! unless event.is_a?(Hash) && event['all_day'] == false
        start_at, end_at = timestamp!(event['start_at']), timestamp!(event['end_at'])
        reject! unless start_at < end_at && start_at >= @now
      end
      reject! if events.length == 2 && timestamp!(events[0]['end_at']) > timestamp!(events[1]['start_at'])
      validate_result!(routing['result'], events, routing)
      [routing, events]
    end

    def validate_result!(result, events, routing)
      reject! unless result.is_a?(Hash)
      duration, distance, walking = result.values_at('duration_seconds', 'distance_meters', 'walking_seconds')
      reject! unless duration.is_a?(Integer) && duration.positive? && duration <= 604_800 &&
        distance.is_a?(Integer) && distance >= 0 && walking.is_a?(Integer) && walking.between?(0, duration)
      departure, arrival = timestamp!(result['departure_time']), timestamp!(result['arrival_time'])
      reject! unless departure < arrival && (duration - (arrival - departure)).abs <= 1
      travel = events.first
      reject! unless departure >= timestamp!(travel['start_at']) && arrival <= timestamp!(travel['end_at']) &&
        duration <= (timestamp!(travel['end_at']) - timestamp!(travel['start_at'])).ceil
      request = routing.fetch('request')
      reject! if request['departure_time'] && departure < timestamp!(request['departure_time'])
      reject! if request['arrival_time'] && arrival > timestamp!(request['arrival_time'])
      buffer = routing.fetch('arrival_buffer_minutes', 0)
      reject! unless buffer.is_a?(Integer) && buffer.between?(0, 180)
      reject! if events.length == 2 && arrival + buffer * 60 > timestamp!(events[1]['start_at'])
    end

    def validate_freshness!(routing)
      checked_at = timestamp!(routing['checked_at'])
      expires_at = timestamp!(routing['expires_at'])
      reject! unless checked_at <= @now && expires_at == checked_at + LIFETIME_SECONDS
      raise Rejected, EXPIRED_MESSAGE if @now >= expires_at
    end

    def validate_places!(routing)
      bindings = routing.fetch('place_bindings', [])
      reject! unless bindings.is_a?(Array) && bindings.length <= 2
      bindings.each do |binding|
        reject! unless binding.is_a?(Hash) && binding['id'].is_a?(Integer)
        place = @user.user_places.active.find_by(id: binding['id'])
        reject! unless place && %w[place_name address_text label kind].all? do |field|
          binding.key?(field) && binding[field].to_s == place.public_send(field).to_s
        end
      end
    end

    def validate_calendar!(events)
      first_start = timestamp!(events.first['start_at'])
      final_end = timestamp!(events.last['end_at'])
      scope = canonical_calendar_scope
      reject! if scope.where('start_at IS NULL OR end_at IS NULL OR end_at <= start_at').exists?
      # This intentionally includes the wait/arrival-buffer gap in a two-event
      # bundle. AI disclosure limits and group filtering must not truncate it.
      reject! if scope.where('start_at < ? AND end_at > ?', final_end, first_start).exists?
    end

    def lock_calendar!
      reject! unless Event.connection.transaction_open?

      # accept_copy holds the user's row lock against new owner/participant FK
      # inserts. Lock every current personal Event too: an existing event outside
      # this interval must not be moved into it after the final conflict scan.
      # The bounded provider call runs while these locks remain held until commit.
      canonical_calendar_scope.select(:id).order(:id).lock('FOR SHARE').load
    end

    def canonical_calendar_scope
      owned_ids = @user.created_events.select(:id)
      participating_ids = @user.participating_events.select(:id)
      Event.where(id: owned_ids).or(Event.where(id: participating_ids))
    end

    def validate_buffer!(routing)
      context = routing['buffer_context']
      return if context.nil?

      reject! unless context.is_a?(Hash) && context.keys.sort ==
        %w[destination_name explicit_minutes origin_name preference_keys transport_modes]
      keys, modes = context.values_at('preference_keys', 'transport_modes')
      allowed_keys = %w[meeting hospital travel business_trip default].map { |kind| "arrival_buffer.#{kind}" }
      reject! unless keys.is_a?(Array) && keys.uniq == keys && (keys - allowed_keys).empty?
      reject! unless modes.is_a?(Array) && modes.length <= 1 && (modes - %w[train bus public_transport car walk]).empty?
      reject! unless %w[origin_name destination_name].all? { |key| context[key].is_a?(String) && context[key].present? }
      values = [buffer_integer!(context['explicit_minutes'])]
      @user.ai_user_preferences.where(key: keys).pluck(:value).each { |value| values << buffer_integer!(value) }
      @user.user_travel_routes.active.where(transport_mode: modes).find_each do |route|
        next unless normalized_place(route.origin_name) == normalized_place(context['origin_name']) &&
          normalized_place(route.destination_name) == normalized_place(context['destination_name'])
        values << buffer_integer!(route.arrival_buffer_minutes) unless route.arrival_buffer_minutes.nil?
      end
      reject! unless values.max <= routing.fetch('arrival_buffer_minutes', 0)
    end

    def buffer_integer!(value)
      parsed = if value.is_a?(Integer)
                 value
               elsif value.is_a?(String) && value.match?(/\A\d{1,3}\z/)
                 value.to_i
               end
      reject! unless parsed && parsed.between?(0, 180)
      parsed
    end

    def normalized_place(value)
      value.unicode_normalize(:nfkc).downcase.gsub(/\s+/, '')
    end

    def approval_digest(payload)
      Digest::SHA256.hexdigest(JSON.generate(canonical(
        'events' => payload['events'].map { |event| event.slice('start_at', 'end_at', 'all_day', 'location') },
        'routing' => payload.fetch('routing').except('approval_digest')
      )))
    end

    def canonical(value)
      case value
      when Hash then value.keys.sort.to_h { |key| [key, canonical(value[key])] }
      when Array then value.map { |child| canonical(child) }
      else value
      end
    end

    def timestamp!(value)
      reject! unless value.is_a?(String)
      match = /\A(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):([0-5]\d)(?:\.\d{1,9})?(Z|[+-]\d{2}:\d{2})\z/.match(value)
      reject! unless match && Date.valid_date?(*match.captures.first(3).map(&:to_i)) &&
        match[4].to_i < 24 && match[5].to_i < 60
      reject! if match[7] != 'Z' && (match[7][1, 2].to_i >= 24 || match[7][4, 2].to_i >= 60)
      Time.iso8601(value)
    rescue ArgumentError
      reject!
    end

    def reject!
      raise Rejected, FAILURE_MESSAGE
    end
  end
end
